const myArray=[1,2,3,4,5]
console.log(myArray)
console.log(myArray[0])
console.log(myArray.indexOf(9))
console.log(myArray.slice(1,3))
console.log(myArray)
console.log(myArray.splice(1,3))
console.log(myArray)
console.log(myArray.length)
myArray.push(9)
console.log(myArray)
myArray.shift()
console.log(myArray)
myArray.pop()
console.log(myArray)
myArray.unshift(12)
console.log(myArray)